package CustomEssentials.Events.ShopInfo;

import java.util.HashMap;

import org.bukkit.Material;

public class ItemPrices {
	
	HashMap<Material,Float> itemBuyPrice = new HashMap<Material, Float>();
	HashMap<Material,Float> itemSellPrice = new HashMap<Material, Float>();
	HashMap<Integer,Integer> itemSlotPriceMultiplier = new HashMap<Integer, Integer>();

	public ItemPrices() {
		setItemBuyPrices();
		setItemSellPrices();
		setItemSlotPrice();
		
	}
	
	public void setItemBuyPrices() {
		
		this.itemBuyPrice.put(Material.STONE, (float) 25.0);
		this.itemBuyPrice.put(Material.COBBLESTONE, (float) 10.0);
		this.itemBuyPrice.put(Material.MOSSY_COBBLESTONE, (float) 50.0);
		this.itemBuyPrice.put(Material.GRANITE, (float) 30.0);
		this.itemBuyPrice.put(Material.DIORITE, (float) 30.0);
		this.itemBuyPrice.put(Material.ANDESITE, (float) 30.0);
		this.itemBuyPrice.put(Material.STONE_BRICKS, (float) 26.0);
		this.itemBuyPrice.put(Material.MOSSY_STONE_BRICKS, (float) 76.0);
		this.itemBuyPrice.put(Material.CRACKED_STONE_BRICKS, (float) 30.0);
		this.itemBuyPrice.put(Material.CHISELED_STONE_BRICKS, (float) 27.0);
		this.itemBuyPrice.put(Material.POLISHED_GRANITE, (float) 31.0);
		this.itemBuyPrice.put(Material.POLISHED_DIORITE, (float) 31.0);
		this.itemBuyPrice.put(Material.POLISHED_ANDESITE, (float) 31.0);
		this.itemBuyPrice.put(Material.DIRT, (float) 55.0);
		this.itemBuyPrice.put(Material.ROOTED_DIRT, (float) 75.0);
		this.itemBuyPrice.put(Material.GRASS_BLOCK, (float) 100.0);
		this.itemBuyPrice.put(Material.PODZOL, (float) 135.0);
		this.itemBuyPrice.put(Material.MYCELIUM, (float) 500.0);
		this.itemBuyPrice.put(Material.SAND, (float) 40.0);
		this.itemBuyPrice.put(Material.RED_SAND, (float) 65.0);
		this.itemBuyPrice.put(Material.SANDSTONE, (float) 160.0);
		this.itemBuyPrice.put(Material.RED_SANDSTONE, (float) 260.0);
		this.itemBuyPrice.put(Material.SMOOTH_SANDSTONE, (float) 161.0);
		this.itemBuyPrice.put(Material.SMOOTH_RED_SANDSTONE, (float) 261.0);
		this.itemBuyPrice.put(Material.CHISELED_SANDSTONE, (float) 161.0);
		this.itemBuyPrice.put(Material.CHISELED_RED_SANDSTONE, (float) 261.0);
		this.itemBuyPrice.put(Material.OAK_PLANKS, (float) 10.0);
		this.itemBuyPrice.put(Material.BIRCH_PLANKS, (float) 12.5);
		this.itemBuyPrice.put(Material.SPRUCE_PLANKS, (float) 15.0);
		this.itemBuyPrice.put(Material.DARK_OAK_PLANKS, (float) 20.0);
		this.itemBuyPrice.put(Material.JUNGLE_PLANKS, (float) 25.0);
		this.itemBuyPrice.put(Material.ACACIA_PLANKS, (float) 30.0);
		this.itemBuyPrice.put(Material.OAK_LOG, (float) 40.0);
		this.itemBuyPrice.put(Material.BIRCH_LOG, (float) 48.0);
		this.itemBuyPrice.put(Material.SPRUCE_LOG, (float) 60.0);
		this.itemBuyPrice.put(Material.DARK_OAK_LOG, (float) 80.0);
		this.itemBuyPrice.put(Material.JUNGLE_LOG, (float) 100.0);
		this.itemBuyPrice.put(Material.ACACIA_LOG, (float) 120.0);
		this.itemBuyPrice.put(Material.GRAVEL, (float) 20.0);
		this.itemBuyPrice.put(Material.CLAY, (float) 40.0);
		this.itemBuyPrice.put(Material.BRICKS, (float) 100.0);
		this.itemBuyPrice.put(Material.SNOW_BLOCK, (float) 15.0);
		this.itemBuyPrice.put(Material.ICE, (float) 35.0);
		this.itemBuyPrice.put(Material.PACKED_ICE, (float) 320.0);
		this.itemBuyPrice.put(Material.BLUE_ICE, (float) 2900.0);
		this.itemBuyPrice.put(Material.OBSIDIAN, (float) 1000.0);
		this.itemBuyPrice.put(Material.PRISMARINE, (float) 250.0);
		this.itemBuyPrice.put(Material.PRISMARINE_BRICKS, (float) 350.0);
		this.itemBuyPrice.put(Material.DARK_PRISMARINE, (float) 500.0);
		this.itemBuyPrice.put(Material.SEA_LANTERN, (float) 500.0);
		this.itemBuyPrice.put(Material.DEAD_TUBE_CORAL_BLOCK, (float) 10.0);
		this.itemBuyPrice.put(Material.DEAD_BRAIN_CORAL_BLOCK, (float) 10.0);
		this.itemBuyPrice.put(Material.DEAD_BUBBLE_CORAL_BLOCK, (float) 10.0);
		this.itemBuyPrice.put(Material.DEAD_FIRE_CORAL_BLOCK, (float) 10.0);
		this.itemBuyPrice.put(Material.DEAD_HORN_CORAL_BLOCK, (float) 10.0);
		this.itemBuyPrice.put(Material.TUBE_CORAL_BLOCK, (float) 200.0);
		this.itemBuyPrice.put(Material.BRAIN_CORAL_BLOCK, (float) 200.0);
		this.itemBuyPrice.put(Material.BUBBLE_CORAL_BLOCK, (float) 200.0);
		this.itemBuyPrice.put(Material.FIRE_CORAL_BLOCK, (float) 200.0);
		this.itemBuyPrice.put(Material.HORN_CORAL_BLOCK, (float) 200.0);
		this.itemBuyPrice.put(Material.NETHERRACK, (float) 5.0);
		this.itemBuyPrice.put(Material.CRIMSON_NYLIUM, (float) 100.0);
		this.itemBuyPrice.put(Material.WARPED_NYLIUM, (float) 100.0);
		this.itemBuyPrice.put(Material.NETHER_BRICKS, (float) 21.0);
		this.itemBuyPrice.put(Material.RED_NETHER_BRICKS, (float) 35.0);
		this.itemBuyPrice.put(Material.CRACKED_NETHER_BRICKS, (float) 36.0);
		this.itemBuyPrice.put(Material.CHISELED_NETHER_BRICKS, (float) 37.0);
		this.itemBuyPrice.put(Material.CRIMSON_PLANKS, (float) 45.0);
		this.itemBuyPrice.put(Material.WARPED_PLANKS, (float) 50.0);
		this.itemBuyPrice.put(Material.CRIMSON_STEM, (float) 150.0);
		this.itemBuyPrice.put(Material.WARPED_STEM, (float) 175.0);
		this.itemBuyPrice.put(Material.WARPED_HYPHAE, (float) 200.0);
		this.itemBuyPrice.put(Material.NETHER_WART_BLOCK, (float) 90.0);
		this.itemBuyPrice.put(Material.WARPED_WART_BLOCK, (float) 90.0);
		this.itemBuyPrice.put(Material.SOUL_SAND, (float) 300.0);
		this.itemBuyPrice.put(Material.MAGMA_BLOCK, (float) 500.0);
		this.itemBuyPrice.put(Material.GLOWSTONE, (float) 80.0);
		this.itemBuyPrice.put(Material.BONE_BLOCK, (float) 100.0);
		this.itemBuyPrice.put(Material.BLACKSTONE, (float) 80.0);
		this.itemBuyPrice.put(Material.POLISHED_BLACKSTONE, (float) 81.0);
		this.itemBuyPrice.put(Material.POLISHED_BLACKSTONE_BRICKS, (float) 160.0);
		this.itemBuyPrice.put(Material.CRACKED_POLISHED_BLACKSTONE_BRICKS, (float) 161.0);
		this.itemBuyPrice.put(Material.CRYING_OBSIDIAN, (float) 1300.0);
		this.itemBuyPrice.put(Material.QUARTZ_BLOCK, (float) 250.0);
		this.itemBuyPrice.put(Material.CHISELED_QUARTZ_BLOCK, (float) 251.0);
		this.itemBuyPrice.put(Material.QUARTZ_PILLAR, (float) 300.0);
		this.itemBuyPrice.put(Material.END_STONE, (float) 100.0);
		this.itemBuyPrice.put(Material.PURPUR_BLOCK, (float) 500.0);
		this.itemBuyPrice.put(Material.PURPUR_PILLAR, (float) 700.0);
		
		this.itemBuyPrice.put(Material.GLASS, (float) 200.0);
		this.itemBuyPrice.put(Material.WHITE_STAINED_GLASS, (float) 250.0);
		this.itemBuyPrice.put(Material.ORANGE_STAINED_GLASS, (float) 250.0);
		this.itemBuyPrice.put(Material.MAGENTA_STAINED_GLASS, (float) 250.0);
		this.itemBuyPrice.put(Material.LIGHT_BLUE_STAINED_GLASS, (float) 250.0);
		this.itemBuyPrice.put(Material.YELLOW_STAINED_GLASS, (float) 250.0);
		this.itemBuyPrice.put(Material.LIME_STAINED_GLASS, (float) 250.0);
		this.itemBuyPrice.put(Material.PINK_STAINED_GLASS, (float) 250.0);
		this.itemBuyPrice.put(Material.GRAY_STAINED_GLASS, (float) 250.0);
		this.itemBuyPrice.put(Material.LIGHT_GRAY_STAINED_GLASS, (float) 250.0);
		this.itemBuyPrice.put(Material.CYAN_STAINED_GLASS, (float) 250.0);
		this.itemBuyPrice.put(Material.PURPLE_STAINED_GLASS, (float) 250.0);
		this.itemBuyPrice.put(Material.BLUE_STAINED_GLASS, (float) 250.0);
		this.itemBuyPrice.put(Material.BROWN_STAINED_GLASS, (float) 250.0);
		this.itemBuyPrice.put(Material.GREEN_STAINED_GLASS, (float) 250.0);
		this.itemBuyPrice.put(Material.RED_STAINED_GLASS, (float) 250.0);
		this.itemBuyPrice.put(Material.TINTED_GLASS, (float) 300.0);	
		this.itemBuyPrice.put(Material.WHITE_WOOL, (float) 80.0);
		this.itemBuyPrice.put(Material.ORANGE_WOOL, (float) 80.0);
		this.itemBuyPrice.put(Material.MAGENTA_WOOL, (float) 80.0);
		this.itemBuyPrice.put(Material.LIGHT_BLUE_WOOL, (float) 80.0);
		this.itemBuyPrice.put(Material.YELLOW_WOOL, (float) 80.0);
		this.itemBuyPrice.put(Material.LIME_WOOL, (float) 80.0);
		this.itemBuyPrice.put(Material.PINK_WOOL, (float) 80.0);
		this.itemBuyPrice.put(Material.GRAY_WOOL, (float) 80.0);
		this.itemBuyPrice.put(Material.LIGHT_GRAY_WOOL, (float) 80.0);
		this.itemBuyPrice.put(Material.CYAN_WOOL, (float) 80.0);
		this.itemBuyPrice.put(Material.PURPLE_WOOL, (float) 80.0);
		this.itemBuyPrice.put(Material.BLUE_WOOL, (float) 80.0);
		this.itemBuyPrice.put(Material.BROWN_WOOL, (float) 80.0);
		this.itemBuyPrice.put(Material.GREEN_WOOL, (float) 80.0);
		this.itemBuyPrice.put(Material.RED_WOOL, (float) 80.0);
		this.itemBuyPrice.put(Material.TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.WHITE_TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.ORANGE_TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.MAGENTA_TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.LIGHT_BLUE_TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.YELLOW_TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.LIME_TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.PINK_TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.GRAY_TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.LIGHT_GRAY_TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.CYAN_TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.PURPLE_TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.BLUE_TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.BROWN_TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.GREEN_TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.RED_TERRACOTTA, (float) 150.0);
		this.itemBuyPrice.put(Material.WHITE_GLAZED_TERRACOTTA, (float) 200);
		this.itemBuyPrice.put(Material.ORANGE_GLAZED_TERRACOTTA, (float) 200);
		this.itemBuyPrice.put(Material.MAGENTA_GLAZED_TERRACOTTA, (float) 200);
		this.itemBuyPrice.put(Material.YELLOW_GLAZED_TERRACOTTA, (float) 200);
		this.itemBuyPrice.put(Material.LIME_GLAZED_TERRACOTTA, (float) 200);
		this.itemBuyPrice.put(Material.PINK_GLAZED_TERRACOTTA, (float) 200);
		this.itemBuyPrice.put(Material.GRAY_GLAZED_TERRACOTTA, (float) 200);
		this.itemBuyPrice.put(Material.CYAN_GLAZED_TERRACOTTA, (float) 200);
		this.itemBuyPrice.put(Material.PURPLE_GLAZED_TERRACOTTA, (float) 200);
		this.itemBuyPrice.put(Material.BLUE_GLAZED_TERRACOTTA, (float) 200);
		this.itemBuyPrice.put(Material.BROWN_GLAZED_TERRACOTTA, (float) 200);
		this.itemBuyPrice.put(Material.GREEN_GLAZED_TERRACOTTA, (float) 200);
		this.itemBuyPrice.put(Material.RED_GLAZED_TERRACOTTA, (float) 200);
		this.itemBuyPrice.put(Material.WHITE_CONCRETE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.ORANGE_CONCRETE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.MAGENTA_CONCRETE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.LIGHT_BLUE_CONCRETE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.YELLOW_CONCRETE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.LIME_CONCRETE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.PINK_CONCRETE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.GRAY_CONCRETE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.LIGHT_GRAY_CONCRETE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.CYAN_CONCRETE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.PURPLE_CONCRETE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.BLUE_CONCRETE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.BROWN_CONCRETE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.GREEN_CONCRETE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.RED_CONCRETE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.WHITE_CONCRETE, (float) 200.0);
		this.itemBuyPrice.put(Material.ORANGE_CONCRETE, (float) 200.0);
		this.itemBuyPrice.put(Material.MAGENTA_CONCRETE, (float) 200.0);
		this.itemBuyPrice.put(Material.LIGHT_BLUE_CONCRETE, (float) 200.0);
		this.itemBuyPrice.put(Material.YELLOW_CONCRETE, (float) 200.0);
		this.itemBuyPrice.put(Material.LIME_CONCRETE, (float) 200.0);
		this.itemBuyPrice.put(Material.PINK_CONCRETE, (float) 200.0);
		this.itemBuyPrice.put(Material.GRAY_CONCRETE, (float) 200.0);
		this.itemBuyPrice.put(Material.LIGHT_GRAY_CONCRETE, (float) 200.0);
		this.itemBuyPrice.put(Material.CYAN_CONCRETE, (float) 200.0);
		this.itemBuyPrice.put(Material.PURPLE_CONCRETE, (float) 200.0);
		this.itemBuyPrice.put(Material.BLUE_CONCRETE, (float) 200.0);
		this.itemBuyPrice.put(Material.BROWN_CONCRETE, (float) 200.0);
		this.itemBuyPrice.put(Material.GREEN_CONCRETE, (float) 200.0);
		this.itemBuyPrice.put(Material.RED_CONCRETE, (float) 200.0);
		
		this.itemBuyPrice.put(Material.TORCH, (float) 10.0);
		this.itemBuyPrice.put(Material.SOUL_TORCH, (float) 30.0);
		this.itemBuyPrice.put(Material.IRON_BARS, (float) 35.0);
		this.itemBuyPrice.put(Material.CHAIN, (float) 5.0);
		this.itemBuyPrice.put(Material.LILY_PAD, (float) 350.0);
		this.itemBuyPrice.put(Material.OAK_SAPLING, (float) 500.0);
		this.itemBuyPrice.put(Material.BIRCH_SAPLING, (float) 650.0);
		this.itemBuyPrice.put(Material.SPRUCE_SAPLING, (float) 750.0);
		this.itemBuyPrice.put(Material.DARK_OAK_SAPLING, (float) 900.0);
		this.itemBuyPrice.put(Material.JUNGLE_SAPLING, (float) 1000.0);
		this.itemBuyPrice.put(Material.ACACIA_SAPLING, (float) 1250.0);
		this.itemBuyPrice.put(Material.OAK_LEAVES, (float) 10.0);
		this.itemBuyPrice.put(Material.BIRCH_LEAVES, (float) 10.0);
		this.itemBuyPrice.put(Material.SPRUCE_LEAVES, (float) 10.0);
		this.itemBuyPrice.put(Material.DARK_OAK_LEAVES, (float) 10.0);
		this.itemBuyPrice.put(Material.JUNGLE_LEAVES, (float) 10.0);
		this.itemBuyPrice.put(Material.ACACIA_LEAVES, (float) 10.0);
		this.itemBuyPrice.put(Material.AZALEA_LEAVES, (float) 10.0);
		this.itemBuyPrice.put(Material.FLOWERING_AZALEA_LEAVES, (float) 25.0);
		this.itemBuyPrice.put(Material.GRASS, (float) 10.0);
		this.itemBuyPrice.put(Material.FERN, (float) 10.0);
		this.itemBuyPrice.put(Material.AZALEA, (float) 100.0);
		this.itemBuyPrice.put(Material.FLOWERING_AZALEA, (float) 150.0);
		this.itemBuyPrice.put(Material.DEAD_BUSH, (float) 8.0);
		this.itemBuyPrice.put(Material.SEAGRASS, (float) 20.0);
		this.itemBuyPrice.put(Material.SEA_PICKLE, (float) 500.0);
		this.itemBuyPrice.put(Material.DANDELION, (float) 100);
		this.itemBuyPrice.put(Material.POPPY, (float) 100);
		this.itemBuyPrice.put(Material.BLUE_ORCHID, (float) 100);
		this.itemBuyPrice.put(Material.ALLIUM, (float) 100);
		this.itemBuyPrice.put(Material.AZURE_BLUET, (float) 100);
		this.itemBuyPrice.put(Material.RED_TULIP, (float) 100);
		this.itemBuyPrice.put(Material.ORANGE_TULIP, (float) 100);
		this.itemBuyPrice.put(Material.WHITE_TULIP, (float) 100);
		this.itemBuyPrice.put(Material.PINK_TULIP, (float) 100);
		this.itemBuyPrice.put(Material.OXEYE_DAISY, (float) 100);
		this.itemBuyPrice.put(Material.CORNFLOWER, (float) 100);
		this.itemBuyPrice.put(Material.LILY_OF_THE_VALLEY, (float) 100);
		this.itemBuyPrice.put(Material.WITHER_ROSE, (float) 250);
		this.itemBuyPrice.put(Material.SPORE_BLOSSOM, (float) 100);
		this.itemBuyPrice.put(Material.ORANGE_TULIP, (float) 100);
		this.itemBuyPrice.put(Material.SUNFLOWER, (float) 100);
		this.itemBuyPrice.put(Material.LILAC, (float) 100);
		this.itemBuyPrice.put(Material.ROSE_BUSH, (float) 100);
		this.itemBuyPrice.put(Material.ORANGE_TULIP, (float) 100);
		this.itemBuyPrice.put(Material.PEONY, (float) 100);
		this.itemBuyPrice.put(Material.TALL_GRASS, (float) 20.0);
		this.itemBuyPrice.put(Material.LARGE_FERN, (float) 20.0);		
		this.itemBuyPrice.put(Material.CRIMSON_ROOTS, (float) 20.0);
		this.itemBuyPrice.put(Material.WARPED_ROOTS, (float) 20.0);
		this.itemBuyPrice.put(Material.NETHER_SPROUTS, (float) 25.0);
		this.itemBuyPrice.put(Material.ORANGE_TULIP, (float) 100.0);
		this.itemBuyPrice.put(Material.MOSS_BLOCK, (float) 800.0);
		this.itemBuyPrice.put(Material.HANGING_ROOTS, (float) 90.0);
		this.itemBuyPrice.put(Material.BIG_DRIPLEAF, (float) 3000.0);
		this.itemBuyPrice.put(Material.SMALL_DRIPLEAF, (float) 1000.0);
		this.itemBuyPrice.put(Material.TUBE_CORAL, (float) 9509500.0);
		this.itemBuyPrice.put(Material.BUBBLE_CORAL, (float) 9500.0);
		this.itemBuyPrice.put(Material.BRAIN_CORAL, (float) 9500.0);
		this.itemBuyPrice.put(Material.FIRE_CORAL, (float) 9500.0);
		this.itemBuyPrice.put(Material.HORN_CORAL, (float) 9500.0);
		this.itemBuyPrice.put(Material.DEAD_TUBE_CORAL, (float) 9500.0);
		this.itemBuyPrice.put(Material.DEAD_BUBBLE_CORAL, (float) 9500.0);
		this.itemBuyPrice.put(Material.DEAD_BRAIN_CORAL, (float) 9500.0);
		this.itemBuyPrice.put(Material.DEAD_FIRE_CORAL, (float) 9500.0);
		this.itemBuyPrice.put(Material.DEAD_HORN_CORAL, (float) 9500.0);
		this.itemBuyPrice.put(Material.TUBE_CORAL_FAN, (float) 9500.0);
		this.itemBuyPrice.put(Material.BUBBLE_CORAL_FAN, (float) 9500.0);
		this.itemBuyPrice.put(Material.BRAIN_CORAL_FAN, (float) 9500.0);
		this.itemBuyPrice.put(Material.FIRE_CORAL_FAN, (float) 9500.0);
		this.itemBuyPrice.put(Material.HORN_CORAL_FAN, (float) 9500.0);
		this.itemBuyPrice.put(Material.DEAD_TUBE_CORAL_FAN, (float) 9500.0);
		this.itemBuyPrice.put(Material.DEAD_BUBBLE_CORAL_FAN, (float) 9500.0);
		this.itemBuyPrice.put(Material.DEAD_BRAIN_CORAL_FAN, (float) 9500.0);
		this.itemBuyPrice.put(Material.DEAD_FIRE_CORAL_FAN, (float) 9500.0);
		this.itemBuyPrice.put(Material.DEAD_HORN_CORAL_FAN, (float) 9500.0);
		this.itemBuyPrice.put(Material.SHROOMLIGHT, (float) 250.0);
		
		this.itemBuyPrice.put(Material.WHEAT_SEEDS, (float) 15.0);
		this.itemBuyPrice.put(Material.WHEAT, (float) 35.0);
		this.itemBuyPrice.put(Material.BEETROOT_SEEDS, (float) 20.0);
		this.itemBuyPrice.put(Material.BEETROOT, (float) 50.0);
		this.itemBuyPrice.put(Material.CARROT, (float) 90.0);
		this.itemBuyPrice.put(Material.POTATO, (float) 180.0);
		this.itemBuyPrice.put(Material.MELON_SEEDS, (float) 50.0);
		this.itemBuyPrice.put(Material.MELON_SLICE, (float) 15.0);
		this.itemBuyPrice.put(Material.PUMPKIN, (float) 100.0);
		this.itemBuyPrice.put(Material.NETHER_WART, (float) 250.0);
		this.itemBuyPrice.put(Material.SUGAR_CANE, (float) 800.0);
		this.itemBuyPrice.put(Material.CACTUS, (float) 1950.0);
		this.itemBuyPrice.put(Material.BAMBOO, (float) 2670.0);
		this.itemBuyPrice.put(Material.COCOA_BEANS, (float) 3500.0);
		this.itemBuyPrice.put(Material.KELP, (float) 5125.0);
		this.itemBuyPrice.put(Material.VINE, (float) 7600.0);
		this.itemBuyPrice.put(Material.GLOW_LICHEN, (float) 9150.0);
		this.itemBuyPrice.put(Material.RED_MUSHROOM, (float) 11000.0);
		this.itemBuyPrice.put(Material.BROWN_MUSHROOM, (float) 12500.0);
		this.itemBuyPrice.put(Material.TWISTING_VINES, (float) 185000.0);
		this.itemBuyPrice.put(Material.WEEPING_VINES, (float) 256000.0);
		this.itemBuyPrice.put(Material.CRIMSON_FUNGUS, (float) 567000.0);
		this.itemBuyPrice.put(Material.WARPED_FUNGUS, (float) 765000.0);
		
		this.itemBuyPrice.put(Material.ROTTEN_FLESH, (float) 30.0);
		this.itemBuyPrice.put(Material.SPIDER_EYE, (float) 50.0);
		this.itemBuyPrice.put(Material.APPLE, (float) 5.0);
		this.itemBuyPrice.put(Material.GOLDEN_APPLE, (float) 150.0);
		this.itemBuyPrice.put(Material.ENCHANTED_GOLDEN_APPLE, (float) 1000000.0);
		this.itemBuyPrice.put(Material.DRIED_KELP, (float) 5.0);
		this.itemBuyPrice.put(Material.SWEET_BERRIES, (float) 150.0);
		this.itemBuyPrice.put(Material.GLOW_BERRIES, (float) 200.0);
		this.itemBuyPrice.put(Material.COOKIE, (float) 10.0);
		this.itemBuyPrice.put(Material.BREAD, (float) 35.0);
		this.itemBuyPrice.put(Material.POISONOUS_POTATO, (float) 3.0);
		this.itemBuyPrice.put(Material.BAKED_POTATO, (float) 50.0);
		this.itemBuyPrice.put(Material.GOLDEN_CARROT, (float) 2500.0);
		this.itemBuyPrice.put(Material.CHICKEN, (float) 50.0);
		this.itemBuyPrice.put(Material.RABBIT, (float) 75.0);
		this.itemBuyPrice.put(Material.PORKCHOP, (float) 100.0);
		this.itemBuyPrice.put(Material.BEEF, (float) 125.0);
		this.itemBuyPrice.put(Material.MUTTON, (float) 115.0);
		this.itemBuyPrice.put(Material.COOKED_CHICKEN, (float) 75.0);
		this.itemBuyPrice.put(Material.COOKED_RABBIT, (float) 100.0);
		this.itemBuyPrice.put(Material.COOKED_PORKCHOP, (float) 115.0);
		this.itemBuyPrice.put(Material.COOKED_BEEF, (float) 125.0);
		this.itemBuyPrice.put(Material.COOKED_MUTTON, (float) 150.0);
		this.itemBuyPrice.put(Material.SALMON, (float) 150.0);
		this.itemBuyPrice.put(Material.COD, (float) 120.0);
		this.itemBuyPrice.put(Material.TROPICAL_FISH, (float) 275.0);
		this.itemBuyPrice.put(Material.PUFFERFISH, (float) 300.0);
		this.itemBuyPrice.put(Material.COOKED_SALMON, (float) 200.0);
		this.itemBuyPrice.put(Material.COOKED_COD, (float) 150.0);
		this.itemBuyPrice.put(Material.PUMPKIN_PIE, (float) 150.0);
		this.itemBuyPrice.put(Material.MUSHROOM_STEW, (float) 150.0);
		this.itemBuyPrice.put(Material.BEETROOT_SOUP, (float) 100.0);
		this.itemBuyPrice.put(Material.RABBIT_STEW, (float) 200.0);
		this.itemBuyPrice.put(Material.CAKE, (float) 650.0);
		this.itemBuyPrice.put(Material.HONEY_BOTTLE, (float) 150.0);
		this.itemBuyPrice.put(Material.CHORUS_FRUIT, (float) 1525.0);
		
		this.itemBuyPrice.put(Material.ARROW, (float) 25.0);
		this.itemBuyPrice.put(Material.BONE, (float) 50.0);
		this.itemBuyPrice.put(Material.STRING, (float) 75.0);
		this.itemBuyPrice.put(Material.GUNPOWDER, (float) 160.0);
		this.itemBuyPrice.put(Material.GLOWSTONE_DUST, (float) 20.0);
		this.itemBuyPrice.put(Material.LEATHER, (float) 45.0);
		this.itemBuyPrice.put(Material.RABBIT_HIDE, (float) 90.0);
		this.itemBuyPrice.put(Material.FEATHER, (float) 25.0);
		this.itemBuyPrice.put(Material.SLIME_BALL, (float) 100.0);
		this.itemBuyPrice.put(Material.MAGMA_CREAM, (float) 150.0);
		this.itemBuyPrice.put(Material.INK_SAC, (float) 150.0);
		this.itemBuyPrice.put(Material.GLOW_INK_SAC, (float) 200.0);
		this.itemBuyPrice.put(Material.ENDER_PEARL, (float) 500.0);
		this.itemBuyPrice.put(Material.BLAZE_ROD, (float) 300.0);
		this.itemBuyPrice.put(Material.GHAST_TEAR, (float) 1000.0);
		this.itemBuyPrice.put(Material.IRON_INGOT, (float) 500.0);
		this.itemBuyPrice.put(Material.GOLD_NUGGET, (float) 90.0);
		this.itemBuyPrice.put(Material.GOLD_INGOT, (float) 900.0);
		this.itemBuyPrice.put(Material.EMERALD, (float) 9500.0);
		this.itemBuyPrice.put(Material.PRISMARINE_CRYSTALS, (float) 930.0);
		this.itemBuyPrice.put(Material.PRISMARINE_SHARD, (float) 1100.0);
		this.itemBuyPrice.put(Material.PHANTOM_MEMBRANE, (float) 850.0);
		this.itemBuyPrice.put(Material.WITHER_SKELETON_SKULL, (float) 250000.0);	
		
		this.itemBuyPrice.put(Material.COAL, (float) 35.0);
		this.itemBuyPrice.put(Material.RAW_IRON, (float) 350.0);
		this.itemBuyPrice.put(Material.RAW_COPPER, (float) 450.0);
		this.itemBuyPrice.put(Material.COPPER_INGOT, (float) 750.0);
		this.itemBuyPrice.put(Material.LAPIS_LAZULI, (float) 80.0);
		this.itemBuyPrice.put(Material.REDSTONE, (float) 100.0);
		this.itemBuyPrice.put(Material.RAW_GOLD, (float) 780.0);
		this.itemBuyPrice.put(Material.DIAMOND, (float) 7000.0);
		this.itemBuyPrice.put(Material.NETHERITE_SCRAP, (float) 10000.0);
		this.itemBuyPrice.put(Material.NETHERITE_INGOT, (float) 45000.0);
		
		this.itemBuyPrice.put(Material.REDSTONE_TORCH, (float) 110.0);
		this.itemBuyPrice.put(Material.REDSTONE_BLOCK, (float) 901.0);
		this.itemBuyPrice.put(Material.REPEATER, (float) 320.0);
		this.itemBuyPrice.put(Material.COMPARATOR, (float) 500.0);
		this.itemBuyPrice.put(Material.PISTON, (float) 650.0);
		this.itemBuyPrice.put(Material.STICKY_PISTON, (float) 750.0);
		this.itemBuyPrice.put(Material.SLIME_BLOCK, (float) 900.0);
		this.itemBuyPrice.put(Material.HONEY_BLOCK, (float) 600.0);
		this.itemBuyPrice.put(Material.OBSERVER, (float) 950.0);
		this.itemBuyPrice.put(Material.HOPPER, (float) 95000.0);
		this.itemBuyPrice.put(Material.MINECART, (float) 2500.0);
		this.itemBuyPrice.put(Material.RAIL, (float) 350.0);
		this.itemBuyPrice.put(Material.POWERED_RAIL, (float) 910.0);
		this.itemBuyPrice.put(Material.DETECTOR_RAIL, (float) 500.0);
		this.itemBuyPrice.put(Material.ACTIVATOR_RAIL, (float) 650.0);
		this.itemBuyPrice.put(Material.DISPENSER, (float) 150.0);
		this.itemBuyPrice.put(Material.DROPPER, (float) 250.0);
		this.itemBuyPrice.put(Material.LEVER, (float) 15.0);
		this.itemBuyPrice.put(Material.STONE_BUTTON, (float) 25.0);
		this.itemBuyPrice.put(Material.STONE_PRESSURE_PLATE, (float) 50.0);
		this.itemBuyPrice.put(Material.LECTERN, (float) 500.0);
		this.itemBuyPrice.put(Material.TARGET, (float) 300.0);
		this.itemBuyPrice.put(Material.LIGHTNING_ROD, (float) 900.0);
		this.itemBuyPrice.put(Material.DAYLIGHT_DETECTOR, (float) 250.0);
		this.itemBuyPrice.put(Material.TRIPWIRE_HOOK, (float) 250.0);
		this.itemBuyPrice.put(Material.CHEST, (float) 80.0);
		this.itemBuyPrice.put(Material.TRAPPED_CHEST, (float) 330.0);
		this.itemBuyPrice.put(Material.TNT, (float) 1000.0);
		this.itemBuyPrice.put(Material.REDSTONE_LAMP, (float) 400.0);
		this.itemBuyPrice.put(Material.NOTE_BLOCK, (float) 1500.0);
		this.itemBuyPrice.put(Material.IRON_TRAPDOOR, (float) 1500.0);
		
		this.itemBuyPrice.put(Material.ENCHANTING_TABLE, (float) 150000.0);
		this.itemBuyPrice.put(Material.ENDER_CHEST, (float) 280000.0);
		this.itemBuyPrice.put(Material.JUKEBOX, (float) 250.0);
		this.itemBuyPrice.put(Material.ANVIL, (float) 15000.0);
		this.itemBuyPrice.put(Material.PAINTING, (float) 100.0);
		this.itemBuyPrice.put(Material.ITEM_FRAME, (float) 100.0);
		this.itemBuyPrice.put(Material.GLOW_ITEM_FRAME, (float) 150.0);
		this.itemBuyPrice.put(Material.FLOWER_POT, (float) 20.0);
		this.itemBuyPrice.put(Material.ARMOR_STAND, (float) 750.0);
		this.itemBuyPrice.put(Material.WHITE_BANNER, (float) 80.0);
		this.itemBuyPrice.put(Material.LOOM, (float) 250.0);
		this.itemBuyPrice.put(Material.COMPOSTER, (float) 50.0);
		this.itemBuyPrice.put(Material.BARREL, (float) 70.0);
		this.itemBuyPrice.put(Material.FURNACE, (float) 80.0);
		this.itemBuyPrice.put(Material.SMOKER, (float) 100.0);
		this.itemBuyPrice.put(Material.BLAST_FURNACE, (float) 510.0);
		this.itemBuyPrice.put(Material.CARTOGRAPHY_TABLE, (float) 350.0);
		this.itemBuyPrice.put(Material.FLETCHING_TABLE, (float) 350.0);
		this.itemBuyPrice.put(Material.GRINDSTONE, (float) 250.0);
		this.itemBuyPrice.put(Material.SMITHING_TABLE, (float) 1000.0);
		this.itemBuyPrice.put(Material.STONECUTTER, (float) 250.0);
		this.itemBuyPrice.put(Material.BELL, (float) 800000.0);
		this.itemBuyPrice.put(Material.BEE_NEST, (float) 500.0);
		this.itemBuyPrice.put(Material.BEEHIVE, (float) 1500.0);
		this.itemBuyPrice.put(Material.LODESTONE, (float) 950.0);
		this.itemBuyPrice.put(Material.RESPAWN_ANCHOR, (float) 9500.0);
		this.itemBuyPrice.put(Material.CANDLE, (float) 10.0);
		this.itemBuyPrice.put(Material.POINTED_DRIPSTONE, (float) 980.0);
		this.itemBuyPrice.put(Material.SCAFFOLDING, (float) 100.0);
		this.itemBuyPrice.put(Material.BUCKET, (float) 500.0);
		this.itemBuyPrice.put(Material.WATER_BUCKET, (float) 750.0);
		this.itemBuyPrice.put(Material.LAVA_BUCKET, (float) 2500.0);
		this.itemBuyPrice.put(Material.POWDER_SNOW_BUCKET, (float) 1750.0);
		this.itemBuyPrice.put(Material.NAME_TAG, (float) 10000.0);
		this.itemBuyPrice.put(Material.BOOK, (float) 350.0);
		
		this.itemBuyPrice.put(Material.BREWING_STAND, (float) 310.0);
		this.itemBuyPrice.put(Material.CAULDRON, (float) 3500.0);
		this.itemBuyPrice.put(Material.POTION, (float) 80.0);
		this.itemBuyPrice.put(Material.BLAZE_POWDER, (float) 150.0);
		this.itemBuyPrice.put(Material.SUGAR, (float) 400.0);
		this.itemBuyPrice.put(Material.FERMENTED_SPIDER_EYE, (float) 200.0);
		this.itemBuyPrice.put(Material.GLISTERING_MELON_SLICE, (float) 50.0);
	}
	
	public void setItemSellPrices() {
		this.itemSellPrice.put(Material.STONE, (float) ((float) 0.04 *  25.0));
		this.itemSellPrice.put(Material.COBBLESTONE, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.MOSSY_COBBLESTONE, (float) ((float) 0.04 *  50.0));
		this.itemSellPrice.put(Material.GRANITE, (float) ((float) 0.04 *  30.0));
		this.itemSellPrice.put(Material.DIORITE, (float) ((float) 0.04 *  30.0));
		this.itemSellPrice.put(Material.ANDESITE, (float) ((float) 0.04 *  30.0));
		this.itemSellPrice.put(Material.STONE_BRICKS, (float) ((float) 0.04 *  26.0));
		this.itemSellPrice.put(Material.MOSSY_STONE_BRICKS, (float) ((float) 0.04 *  76.0));
		this.itemSellPrice.put(Material.CRACKED_STONE_BRICKS, (float) ((float) 0.04 *  30.0));
		this.itemSellPrice.put(Material.CHISELED_STONE_BRICKS, (float) ((float) 0.04 *  27.0));
		this.itemSellPrice.put(Material.POLISHED_GRANITE, (float) ((float) 0.04 *  31.0));
		this.itemSellPrice.put(Material.POLISHED_DIORITE, (float) ((float) 0.04 *  31.0));
		this.itemSellPrice.put(Material.POLISHED_ANDESITE, (float) ((float) 0.04 *  31.0));
		this.itemSellPrice.put(Material.DIRT, (float) ((float) 0.04 *  55.0));
		this.itemSellPrice.put(Material.ROOTED_DIRT, (float) ((float) 0.04 *  75.0));
		this.itemSellPrice.put(Material.GRASS_BLOCK, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.PODZOL, (float) ((float) 0.04 *  135.0));
		this.itemSellPrice.put(Material.MYCELIUM, (float) ((float) 0.04 *  500.0));
		this.itemSellPrice.put(Material.SAND, (float) ((float) 0.04 *  40.0));
		this.itemSellPrice.put(Material.RED_SAND, (float) ((float) 0.04 *  65.0));
		this.itemSellPrice.put(Material.SANDSTONE, (float) ((float) 0.04 *  160.0));
		this.itemSellPrice.put(Material.RED_SANDSTONE, (float) ((float) 0.04 *  260.0));
		this.itemSellPrice.put(Material.SMOOTH_SANDSTONE, (float) ((float) 0.04 *  161.0));
		this.itemSellPrice.put(Material.SMOOTH_RED_SANDSTONE, (float) ((float) 0.04 *  261.0));
		this.itemSellPrice.put(Material.CHISELED_SANDSTONE, (float) ((float) 0.04 *  161.0));
		this.itemSellPrice.put(Material.CHISELED_RED_SANDSTONE, (float) ((float) 0.04 *  261.0));
		this.itemSellPrice.put(Material.OAK_PLANKS, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.BIRCH_PLANKS, (float) ((float) 0.04 *  12.5));
		this.itemSellPrice.put(Material.SPRUCE_PLANKS, (float) ((float) 0.04 *  15.0));
		this.itemSellPrice.put(Material.DARK_OAK_PLANKS, (float) ((float) 0.04 *  20.0));
		this.itemSellPrice.put(Material.JUNGLE_PLANKS, (float) ((float) 0.04 *  25.0));
		this.itemSellPrice.put(Material.ACACIA_PLANKS, (float) ((float) 0.04 *  30.0));
		this.itemSellPrice.put(Material.OAK_LOG, (float) ((float) 0.04 *  40.0));
		this.itemSellPrice.put(Material.BIRCH_LOG, (float) ((float) 0.04 *  48.0));
		this.itemSellPrice.put(Material.SPRUCE_LOG, (float) ((float) 0.04 *  60.0));
		this.itemSellPrice.put(Material.DARK_OAK_LOG, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.JUNGLE_LOG, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.ACACIA_LOG, (float) ((float) 0.04 *  120.0));
		this.itemSellPrice.put(Material.GRAVEL, (float) ((float) 0.04 *  20.0));
		this.itemSellPrice.put(Material.CLAY, (float) ((float) 0.04 *  40.0));
		this.itemSellPrice.put(Material.BRICKS, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.SNOW_BLOCK, (float) ((float) 0.04 *  15.0));
		this.itemSellPrice.put(Material.ICE, (float) ((float) 0.04 *  35.0));
		this.itemSellPrice.put(Material.PACKED_ICE, (float) ((float) 0.04 *  320.0));
		this.itemSellPrice.put(Material.BLUE_ICE, (float) ((float) 0.04 *  2900.0));
		this.itemSellPrice.put(Material.OBSIDIAN, (float) ((float) 0.04 *  1000.0));
		this.itemSellPrice.put(Material.PRISMARINE, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.PRISMARINE_BRICKS, (float) ((float) 0.04 *  350.0));
		this.itemSellPrice.put(Material.DARK_PRISMARINE, (float) ((float) 0.04 *  500.0));
		this.itemSellPrice.put(Material.SEA_LANTERN, (float) ((float) 0.04 *  500.0));
		this.itemSellPrice.put(Material.DEAD_TUBE_CORAL_BLOCK, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.DEAD_BRAIN_CORAL_BLOCK, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.DEAD_BUBBLE_CORAL_BLOCK, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.DEAD_FIRE_CORAL_BLOCK, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.DEAD_HORN_CORAL_BLOCK, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.TUBE_CORAL_BLOCK, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.BRAIN_CORAL_BLOCK, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.BUBBLE_CORAL_BLOCK, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.FIRE_CORAL_BLOCK, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.HORN_CORAL_BLOCK, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.NETHERRACK, (float) ((float) 0.04 *  5.0));
		this.itemSellPrice.put(Material.CRIMSON_NYLIUM, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.WARPED_NYLIUM, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.NETHER_BRICKS, (float) ((float) 0.04 *  21.0));
		this.itemSellPrice.put(Material.RED_NETHER_BRICKS, (float) ((float) 0.04 *  35.0));
		this.itemSellPrice.put(Material.CRACKED_NETHER_BRICKS, (float) ((float) 0.04 *  36.0));
		this.itemSellPrice.put(Material.CHISELED_NETHER_BRICKS, (float) ((float) 0.04 *  37.0));
		this.itemSellPrice.put(Material.CRIMSON_PLANKS, (float) ((float) 0.04 *  45.0));
		this.itemSellPrice.put(Material.WARPED_PLANKS, (float) ((float) 0.04 *  50.0));
		this.itemSellPrice.put(Material.CRIMSON_STEM, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.WARPED_STEM, (float) ((float) 0.04 *  175.0));
		this.itemSellPrice.put(Material.WARPED_HYPHAE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.NETHER_WART_BLOCK, (float) ((float) 0.04 *  90.0));
		this.itemSellPrice.put(Material.WARPED_WART_BLOCK, (float) ((float) 0.04 *  90.0));
		this.itemSellPrice.put(Material.SOUL_SAND, (float) ((float) 0.04 *  300.0));
		this.itemSellPrice.put(Material.MAGMA_BLOCK, (float) ((float) 0.04 *  500.0));
		this.itemSellPrice.put(Material.GLOWSTONE, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.BONE_BLOCK, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.BLACKSTONE, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.POLISHED_BLACKSTONE, (float) ((float) 0.04 *  81.0));
		this.itemSellPrice.put(Material.POLISHED_BLACKSTONE_BRICKS, (float) ((float) 0.04 *  160.0));
		this.itemSellPrice.put(Material.CRACKED_POLISHED_BLACKSTONE_BRICKS, (float) ((float) 0.04 *  161.0));
		this.itemSellPrice.put(Material.CRYING_OBSIDIAN, (float) ((float) 0.04 *  1300.0));
		this.itemSellPrice.put(Material.QUARTZ_BLOCK, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.CHISELED_QUARTZ_BLOCK, (float) ((float) 0.04 *  251.0));
		this.itemSellPrice.put(Material.QUARTZ_PILLAR, (float) ((float) 0.04 *  300.0));
		this.itemSellPrice.put(Material.END_STONE, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.PURPUR_BLOCK, (float) ((float) 0.04 *  500.0));
		this.itemSellPrice.put(Material.PURPUR_PILLAR, (float) ((float) 0.04 *  700.0));
		
		this.itemSellPrice.put(Material.GLASS, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.WHITE_STAINED_GLASS, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.ORANGE_STAINED_GLASS, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.MAGENTA_STAINED_GLASS, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.LIGHT_BLUE_STAINED_GLASS, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.YELLOW_STAINED_GLASS, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.LIME_STAINED_GLASS, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.PINK_STAINED_GLASS, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.GRAY_STAINED_GLASS, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.LIGHT_GRAY_STAINED_GLASS, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.CYAN_STAINED_GLASS, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.PURPLE_STAINED_GLASS, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.BLUE_STAINED_GLASS, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.BROWN_STAINED_GLASS, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.GREEN_STAINED_GLASS, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.RED_STAINED_GLASS, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.TINTED_GLASS, (float) ((float) 0.04 *  300.0));	
		this.itemSellPrice.put(Material.WHITE_WOOL, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.ORANGE_WOOL, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.MAGENTA_WOOL, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.LIGHT_BLUE_WOOL, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.YELLOW_WOOL, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.LIME_WOOL, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.PINK_WOOL, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.GRAY_WOOL, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.LIGHT_GRAY_WOOL, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.CYAN_WOOL, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.PURPLE_WOOL, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.BLUE_WOOL, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.BROWN_WOOL, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.GREEN_WOOL, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.RED_WOOL, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.WHITE_TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.ORANGE_TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.MAGENTA_TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.LIGHT_BLUE_TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.YELLOW_TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.LIME_TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.PINK_TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.GRAY_TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.LIGHT_GRAY_TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.CYAN_TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.PURPLE_TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.BLUE_TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.BROWN_TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.GREEN_TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.RED_TERRACOTTA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.WHITE_GLAZED_TERRACOTTA, (float) ((float) 0.04 *  200));
		this.itemSellPrice.put(Material.ORANGE_GLAZED_TERRACOTTA, (float) ((float) 0.04 *  200));
		this.itemSellPrice.put(Material.MAGENTA_GLAZED_TERRACOTTA, (float) ((float) 0.04 *  200));
		this.itemSellPrice.put(Material.YELLOW_GLAZED_TERRACOTTA, (float) ((float) 0.04 *  200));
		this.itemSellPrice.put(Material.LIME_GLAZED_TERRACOTTA, (float) ((float) 0.04 *  200));
		this.itemSellPrice.put(Material.PINK_GLAZED_TERRACOTTA, (float) ((float) 0.04 *  200));
		this.itemSellPrice.put(Material.GRAY_GLAZED_TERRACOTTA, (float) ((float) 0.04 *  200));
		this.itemSellPrice.put(Material.CYAN_GLAZED_TERRACOTTA, (float) ((float) 0.04 *  200));
		this.itemSellPrice.put(Material.PURPLE_GLAZED_TERRACOTTA, (float) ((float) 0.04 *  200));
		this.itemSellPrice.put(Material.BLUE_GLAZED_TERRACOTTA, (float) ((float) 0.04 *  200));
		this.itemSellPrice.put(Material.BROWN_GLAZED_TERRACOTTA, (float) ((float) 0.04 *  200));
		this.itemSellPrice.put(Material.GREEN_GLAZED_TERRACOTTA, (float) ((float) 0.04 *  200));
		this.itemSellPrice.put(Material.RED_GLAZED_TERRACOTTA, (float) ((float) 0.04 *  200));
		this.itemSellPrice.put(Material.WHITE_CONCRETE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.ORANGE_CONCRETE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.MAGENTA_CONCRETE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.LIGHT_BLUE_CONCRETE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.YELLOW_CONCRETE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.LIME_CONCRETE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.PINK_CONCRETE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.GRAY_CONCRETE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.LIGHT_GRAY_CONCRETE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.CYAN_CONCRETE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.PURPLE_CONCRETE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.BLUE_CONCRETE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.BROWN_CONCRETE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.GREEN_CONCRETE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.RED_CONCRETE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.WHITE_CONCRETE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.ORANGE_CONCRETE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.MAGENTA_CONCRETE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.LIGHT_BLUE_CONCRETE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.YELLOW_CONCRETE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.LIME_CONCRETE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.PINK_CONCRETE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.GRAY_CONCRETE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.LIGHT_GRAY_CONCRETE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.CYAN_CONCRETE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.PURPLE_CONCRETE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.BLUE_CONCRETE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.BROWN_CONCRETE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.GREEN_CONCRETE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.RED_CONCRETE, (float) ((float) 0.04 *  200.0));
		
		this.itemSellPrice.put(Material.TORCH, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.SOUL_TORCH, (float) ((float) 0.04 *  30.0));
		this.itemSellPrice.put(Material.IRON_BARS, (float) ((float) 0.04 *  35.0));
		this.itemSellPrice.put(Material.CHAIN, (float) ((float) 0.04 *  5.0));
		this.itemSellPrice.put(Material.LILY_PAD, (float) ((float) 0.04 *  350.0));
		this.itemSellPrice.put(Material.OAK_SAPLING, (float) ((float) 0.04 *  500.0));
		this.itemSellPrice.put(Material.BIRCH_SAPLING, (float) ((float) 0.04 *  650.0));
		this.itemSellPrice.put(Material.SPRUCE_SAPLING, (float) ((float) 0.04 *  750.0));
		this.itemSellPrice.put(Material.DARK_OAK_SAPLING, (float) ((float) 0.04 *  900.0));
		this.itemSellPrice.put(Material.JUNGLE_SAPLING, (float) ((float) 0.04 *  1000.0));
		this.itemSellPrice.put(Material.ACACIA_SAPLING, (float) ((float) 0.04 *  1250.0));
		this.itemSellPrice.put(Material.OAK_LEAVES, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.BIRCH_LEAVES, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.SPRUCE_LEAVES, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.DARK_OAK_LEAVES, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.JUNGLE_LEAVES, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.ACACIA_LEAVES, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.AZALEA_LEAVES, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.FLOWERING_AZALEA_LEAVES, (float) ((float) 0.04 *  25.0));
		this.itemSellPrice.put(Material.GRASS, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.FERN, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.AZALEA, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.FLOWERING_AZALEA, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.DEAD_BUSH, (float) ((float) 0.04 *  8.0));
		this.itemSellPrice.put(Material.SEAGRASS, (float) ((float) 0.04 *  20.0));
		this.itemSellPrice.put(Material.SEA_PICKLE, (float) ((float) 0.04 *  500.0));
		this.itemSellPrice.put(Material.DANDELION, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.POPPY, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.BLUE_ORCHID, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.ALLIUM, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.AZURE_BLUET, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.RED_TULIP, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.ORANGE_TULIP, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.WHITE_TULIP, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.PINK_TULIP, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.OXEYE_DAISY, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.CORNFLOWER, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.LILY_OF_THE_VALLEY, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.WITHER_ROSE, (float) ((float) 0.04 *  250));
		this.itemSellPrice.put(Material.SPORE_BLOSSOM, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.ORANGE_TULIP, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.SUNFLOWER, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.LILAC, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.ROSE_BUSH, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.ORANGE_TULIP, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.PEONY, (float) ((float) 0.04 *  100));
		this.itemSellPrice.put(Material.TALL_GRASS, (float) ((float) 0.04 *  20.0));
		this.itemSellPrice.put(Material.LARGE_FERN, (float) ((float) 0.04 *  20.0));		
		this.itemSellPrice.put(Material.CRIMSON_ROOTS, (float) ((float) 0.04 *  20.0));
		this.itemSellPrice.put(Material.WARPED_ROOTS, (float) ((float) 0.04 *  20.0));
		this.itemSellPrice.put(Material.NETHER_SPROUTS, (float) ((float) 0.04 *  25.0));
		this.itemSellPrice.put(Material.ORANGE_TULIP, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.MOSS_BLOCK, (float) ((float) 0.04 *  800.0));
		this.itemSellPrice.put(Material.HANGING_ROOTS, (float) ((float) 0.04 *  90.0));
		this.itemSellPrice.put(Material.BIG_DRIPLEAF, (float) ((float) 0.04 *  3000.0));
		this.itemSellPrice.put(Material.SMALL_DRIPLEAF, (float) ((float) 0.04 *  1000.0));
		this.itemSellPrice.put(Material.TUBE_CORAL, (float) ((float) 0.04 *  9509500.0));
		this.itemSellPrice.put(Material.BUBBLE_CORAL, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.BRAIN_CORAL, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.FIRE_CORAL, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.HORN_CORAL, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.DEAD_TUBE_CORAL, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.DEAD_BUBBLE_CORAL, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.DEAD_BRAIN_CORAL, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.DEAD_FIRE_CORAL, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.DEAD_HORN_CORAL, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.TUBE_CORAL_FAN, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.BUBBLE_CORAL_FAN, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.BRAIN_CORAL_FAN, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.FIRE_CORAL_FAN, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.HORN_CORAL_FAN, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.DEAD_TUBE_CORAL_FAN, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.DEAD_BUBBLE_CORAL_FAN, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.DEAD_BRAIN_CORAL_FAN, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.DEAD_FIRE_CORAL_FAN, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.DEAD_HORN_CORAL_FAN, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.SHROOMLIGHT, (float) ((float) 0.04 *  250.0));
		
		this.itemSellPrice.put(Material.WHEAT_SEEDS, (float) ((float) 0.04 *  15.0));
		this.itemSellPrice.put(Material.WHEAT, (float) ((float) 0.04 *  35.0));
		this.itemSellPrice.put(Material.BEETROOT_SEEDS, (float) ((float) 0.04 *  20.0));
		this.itemSellPrice.put(Material.BEETROOT, (float) ((float) 0.04 *  50.0));
		this.itemSellPrice.put(Material.CARROT, (float) ((float) 0.04 *  90.0));
		this.itemSellPrice.put(Material.POTATO, (float) ((float) 0.04 *  180.0));
		this.itemSellPrice.put(Material.MELON_SEEDS, (float) ((float) 0.04 *  50.0));
		this.itemSellPrice.put(Material.MELON_SLICE, (float) ((float) 0.04 *  15.0));
		this.itemSellPrice.put(Material.PUMPKIN, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.NETHER_WART, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.SUGAR_CANE, (float) ((float) 0.04 *  800.0));
		this.itemSellPrice.put(Material.CACTUS, (float) ((float) 0.04 *  1950.0));
		this.itemSellPrice.put(Material.BAMBOO, (float) ((float) 0.04 *  2670.0));
		this.itemSellPrice.put(Material.COCOA_BEANS, (float) ((float) 0.04 *  3500.0));
		this.itemSellPrice.put(Material.KELP, (float) ((float) 0.04 *  5125.0));
		this.itemSellPrice.put(Material.VINE, (float) ((float) 0.04 *  7600.0));
		this.itemSellPrice.put(Material.GLOW_LICHEN, (float) ((float) 0.04 *  9150.0));
		this.itemSellPrice.put(Material.RED_MUSHROOM, (float) ((float) 0.04 *  11000.0));
		this.itemSellPrice.put(Material.BROWN_MUSHROOM, (float) ((float) 0.04 *  12500.0));
		this.itemSellPrice.put(Material.TWISTING_VINES, (float) ((float) 0.04 *  185000.0));
		this.itemSellPrice.put(Material.WEEPING_VINES, (float) ((float) 0.04 *  256000.0));
		this.itemSellPrice.put(Material.CRIMSON_FUNGUS, (float) ((float) 0.04 *  567000.0));
		this.itemSellPrice.put(Material.WARPED_FUNGUS, (float) ((float) 0.04 *  765000.0));
		
		this.itemSellPrice.put(Material.ROTTEN_FLESH, (float) ((float) 0.04 *  30.0));
		this.itemSellPrice.put(Material.SPIDER_EYE, (float) ((float) 0.04 *  50.0));
		this.itemSellPrice.put(Material.APPLE, (float) ((float) 0.04 *  5.0));
		this.itemSellPrice.put(Material.GOLDEN_APPLE, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.ENCHANTED_GOLDEN_APPLE, (float) ((float) 0.04 *  1000000.0));
		this.itemSellPrice.put(Material.DRIED_KELP, (float) ((float) 0.04 *  5.0));
		this.itemSellPrice.put(Material.SWEET_BERRIES, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.GLOW_BERRIES, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.COOKIE, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.BREAD, (float) ((float) 0.04 *  35.0));
		this.itemSellPrice.put(Material.POISONOUS_POTATO, (float) ((float) 0.04 *  3.0));
		this.itemSellPrice.put(Material.BAKED_POTATO, (float) ((float) 0.04 *  50.0));
		this.itemSellPrice.put(Material.GOLDEN_CARROT, (float) ((float) 0.04 *  2500.0));
		this.itemSellPrice.put(Material.CHICKEN, (float) ((float) 0.04 *  50.0));
		this.itemSellPrice.put(Material.RABBIT, (float) ((float) 0.04 *  75.0));
		this.itemSellPrice.put(Material.PORKCHOP, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.BEEF, (float) ((float) 0.04 *  125.0));
		this.itemSellPrice.put(Material.MUTTON, (float) ((float) 0.04 *  115.0));
		this.itemSellPrice.put(Material.COOKED_CHICKEN, (float) ((float) 0.04 *  75.0));
		this.itemSellPrice.put(Material.COOKED_RABBIT, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.COOKED_PORKCHOP, (float) ((float) 0.04 *  115.0));
		this.itemSellPrice.put(Material.COOKED_BEEF, (float) ((float) 0.04 *  125.0));
		this.itemSellPrice.put(Material.COOKED_MUTTON, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.SALMON, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.COD, (float) ((float) 0.04 *  120.0));
		this.itemSellPrice.put(Material.TROPICAL_FISH, (float) ((float) 0.04 *  275.0));
		this.itemSellPrice.put(Material.PUFFERFISH, (float) ((float) 0.04 *  300.0));
		this.itemSellPrice.put(Material.COOKED_SALMON, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.COOKED_COD, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.PUMPKIN_PIE, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.MUSHROOM_STEW, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.BEETROOT_SOUP, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.RABBIT_STEW, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.CAKE, (float) ((float) 0.04 *  650.0));
		this.itemSellPrice.put(Material.HONEY_BOTTLE, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.CHORUS_FRUIT, (float) ((float) 0.04 *  1525.0));
		
		this.itemSellPrice.put(Material.ARROW, (float) ((float) 0.04 *  25.0));
		this.itemSellPrice.put(Material.BONE, (float) ((float) 0.04 *  50.0));
		this.itemSellPrice.put(Material.STRING, (float) ((float) 0.04 *  75.0));
		this.itemSellPrice.put(Material.GUNPOWDER, (float) ((float) 0.04 *  160.0));
		this.itemSellPrice.put(Material.GLOWSTONE_DUST, (float) ((float) 0.04 *  20.0));
		this.itemSellPrice.put(Material.LEATHER, (float) ((float) 0.04 *  45.0));
		this.itemSellPrice.put(Material.RABBIT_HIDE, (float) ((float) 0.04 *  90.0));
		this.itemSellPrice.put(Material.FEATHER, (float) ((float) 0.04 *  25.0));
		this.itemSellPrice.put(Material.SLIME_BALL, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.MAGMA_CREAM, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.INK_SAC, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.GLOW_INK_SAC, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.ENDER_PEARL, (float) ((float) 0.04 *  500.0));
		this.itemSellPrice.put(Material.BLAZE_ROD, (float) ((float) 0.04 *  300.0));
		this.itemSellPrice.put(Material.GHAST_TEAR, (float) ((float) 0.04 *  1000.0));
		this.itemSellPrice.put(Material.IRON_INGOT, (float) ((float) 0.04 *  500.0));
		this.itemSellPrice.put(Material.GOLD_NUGGET, (float) ((float) 0.04 *  90.0));
		this.itemSellPrice.put(Material.GOLD_INGOT, (float) ((float) 0.04 *  900.0));
		this.itemSellPrice.put(Material.EMERALD, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.PRISMARINE_CRYSTALS, (float) ((float) 0.04 *  930.0));
		this.itemSellPrice.put(Material.PRISMARINE_SHARD, (float) ((float) 0.04 *  1100.0));
		this.itemSellPrice.put(Material.PHANTOM_MEMBRANE, (float) ((float) 0.04 *  850.0));
		this.itemSellPrice.put(Material.WITHER_SKELETON_SKULL, (float) ((float) 0.04 *  250000.0));	
		
		this.itemSellPrice.put(Material.COAL, (float) ((float) 0.04 *  35.0));
		this.itemSellPrice.put(Material.RAW_IRON, (float) ((float) 0.04 *  350.0));
		this.itemSellPrice.put(Material.RAW_COPPER, (float) ((float) 0.04 *  450.0));
		this.itemSellPrice.put(Material.COPPER_INGOT, (float) ((float) 0.04 *  750.0));
		this.itemSellPrice.put(Material.LAPIS_LAZULI, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.REDSTONE, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.RAW_GOLD, (float) ((float) 0.04 *  780.0));
		this.itemSellPrice.put(Material.DIAMOND, (float) ((float) 0.04 *  7000.0));
		this.itemSellPrice.put(Material.NETHERITE_SCRAP, (float) ((float) 0.04 *  10000.0));
		this.itemSellPrice.put(Material.NETHERITE_INGOT, (float) ((float) 0.04 *  45000.0));
		
		this.itemSellPrice.put(Material.REDSTONE_TORCH, (float) ((float) 0.04 *  110.0));
		this.itemSellPrice.put(Material.REDSTONE_BLOCK, (float) ((float) 0.04 *  901.0));
		this.itemSellPrice.put(Material.REPEATER, (float) ((float) 0.04 *  320.0));
		this.itemSellPrice.put(Material.COMPARATOR, (float) ((float) 0.04 *  500.0));
		this.itemSellPrice.put(Material.PISTON, (float) ((float) 0.04 *  650.0));
		this.itemSellPrice.put(Material.STICKY_PISTON, (float) ((float) 0.04 *  750.0));
		this.itemSellPrice.put(Material.SLIME_BLOCK, (float) ((float) 0.04 *  900.0));
		this.itemSellPrice.put(Material.HONEY_BLOCK, (float) ((float) 0.04 *  600.0));
		this.itemSellPrice.put(Material.OBSERVER, (float) ((float) 0.04 *  950.0));
		this.itemSellPrice.put(Material.HOPPER, (float) ((float) 0.04 *  95000.0));
		this.itemSellPrice.put(Material.MINECART, (float) ((float) 0.04 *  2500.0));
		this.itemSellPrice.put(Material.RAIL, (float) ((float) 0.04 *  350.0));
		this.itemSellPrice.put(Material.POWERED_RAIL, (float) ((float) 0.04 *  910.0));
		this.itemSellPrice.put(Material.DETECTOR_RAIL, (float) ((float) 0.04 *  500.0));
		this.itemSellPrice.put(Material.ACTIVATOR_RAIL, (float) ((float) 0.04 *  650.0));
		this.itemSellPrice.put(Material.DISPENSER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.DROPPER, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.LEVER, (float) ((float) 0.04 *  15.0));
		this.itemSellPrice.put(Material.STONE_BUTTON, (float) ((float) 0.04 *  25.0));
		this.itemSellPrice.put(Material.STONE_PRESSURE_PLATE, (float) ((float) 0.04 *  50.0));
		this.itemSellPrice.put(Material.LECTERN, (float) ((float) 0.04 *  500.0));
		this.itemSellPrice.put(Material.TARGET, (float) ((float) 0.04 *  300.0));
		this.itemSellPrice.put(Material.LIGHTNING_ROD, (float) ((float) 0.04 *  900.0));
		this.itemSellPrice.put(Material.DAYLIGHT_DETECTOR, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.TRIPWIRE_HOOK, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.CHEST, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.TRAPPED_CHEST, (float) ((float) 0.04 *  330.0));
		this.itemSellPrice.put(Material.TNT, (float) ((float) 0.04 *  1000.0));
		this.itemSellPrice.put(Material.REDSTONE_LAMP, (float) ((float) 0.04 *  400.0));
		this.itemSellPrice.put(Material.NOTE_BLOCK, (float) ((float) 0.04 *  1500.0));
		this.itemSellPrice.put(Material.IRON_TRAPDOOR, (float) ((float) 0.04 *  1500.0));
		
		this.itemSellPrice.put(Material.ENCHANTING_TABLE, (float) ((float) 0.04 *  150000.0));
		this.itemSellPrice.put(Material.ENDER_CHEST, (float) ((float) 0.04 *  280000.0));
		this.itemSellPrice.put(Material.JUKEBOX, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.ANVIL, (float) ((float) 0.04 *  15000.0));
		this.itemSellPrice.put(Material.PAINTING, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.ITEM_FRAME, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.GLOW_ITEM_FRAME, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.FLOWER_POT, (float) ((float) 0.04 *  20.0));
		this.itemSellPrice.put(Material.ARMOR_STAND, (float) ((float) 0.04 *  750.0));
		this.itemSellPrice.put(Material.WHITE_BANNER, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.LOOM, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.COMPOSTER, (float) ((float) 0.04 *  50.0));
		this.itemSellPrice.put(Material.BARREL, (float) ((float) 0.04 *  70.0));
		this.itemSellPrice.put(Material.FURNACE, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.SMOKER, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.BLAST_FURNACE, (float) ((float) 0.04 *  510.0));
		this.itemSellPrice.put(Material.CARTOGRAPHY_TABLE, (float) ((float) 0.04 *  350.0));
		this.itemSellPrice.put(Material.FLETCHING_TABLE, (float) ((float) 0.04 *  350.0));
		this.itemSellPrice.put(Material.GRINDSTONE, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.SMITHING_TABLE, (float) ((float) 0.04 *  1000.0));
		this.itemSellPrice.put(Material.STONECUTTER, (float) ((float) 0.04 *  250.0));
		this.itemSellPrice.put(Material.BELL, (float) ((float) 0.04 *  800000.0));
		this.itemSellPrice.put(Material.BEE_NEST, (float) ((float) 0.04 *  500.0));
		this.itemSellPrice.put(Material.BEEHIVE, (float) ((float) 0.04 *  1500.0));
		this.itemSellPrice.put(Material.LODESTONE, (float) ((float) 0.04 *  950.0));
		this.itemSellPrice.put(Material.RESPAWN_ANCHOR, (float) ((float) 0.04 *  9500.0));
		this.itemSellPrice.put(Material.CANDLE, (float) ((float) 0.04 *  10.0));
		this.itemSellPrice.put(Material.POINTED_DRIPSTONE, (float) ((float) 0.04 *  980.0));
		this.itemSellPrice.put(Material.SCAFFOLDING, (float) ((float) 0.04 *  100.0));
		this.itemSellPrice.put(Material.BUCKET, (float) ((float) 0.04 *  500.0));
		this.itemSellPrice.put(Material.WATER_BUCKET, (float) ((float) 0.04 *  750.0));
		this.itemSellPrice.put(Material.LAVA_BUCKET, (float) ((float) 0.04 *  2500.0));
		this.itemSellPrice.put(Material.POWDER_SNOW_BUCKET, (float) ((float) 0.04 *  1750.0));
		this.itemSellPrice.put(Material.NAME_TAG, (float) ((float) 0.04 *  10000.0));
		this.itemSellPrice.put(Material.BOOK, (float) ((float) 0.04 *  350.0));
		
		this.itemSellPrice.put(Material.BREWING_STAND, (float) ((float) 0.04 *  310.0));
		this.itemSellPrice.put(Material.CAULDRON, (float) ((float) 0.04 *  3500.0));
		this.itemSellPrice.put(Material.POTION, (float) ((float) 0.04 *  80.0));
		this.itemSellPrice.put(Material.BLAZE_POWDER, (float) ((float) 0.04 *  150.0));
		this.itemSellPrice.put(Material.SUGAR, (float) ((float) 0.04 *  400.0));
		this.itemSellPrice.put(Material.FERMENTED_SPIDER_EYE, (float) ((float) 0.04 *  200.0));
		this.itemSellPrice.put(Material.GLISTERING_MELON_SLICE, (float) ((float) 0.04 *  50.0));
	}
	
	public void setItemSlotPrice() {
		this.itemSlotPriceMultiplier.put(10, 1);
		this.itemSlotPriceMultiplier.put(11, 8);
		this.itemSlotPriceMultiplier.put(12, 16);
		this.itemSlotPriceMultiplier.put(13, 32);
		this.itemSlotPriceMultiplier.put(14, 64);
		this.itemSlotPriceMultiplier.put(15, 128);
		this.itemSlotPriceMultiplier.put(16, 256);
		this.itemSlotPriceMultiplier.put(20, 512);
		this.itemSlotPriceMultiplier.put(21, 1024);
		this.itemSlotPriceMultiplier.put(22, 1536);
		this.itemSlotPriceMultiplier.put(23, 2048);
		this.itemSlotPriceMultiplier.put(24, 2304);
	}
	
	public HashMap<Integer, Integer> getItemSlotPriceMultiplier() {
		return itemSlotPriceMultiplier;
	}

	public void setItemSlotPriceMultiplier(HashMap<Integer, Integer> itemSlotPriceMultiplier) {
		this.itemSlotPriceMultiplier = itemSlotPriceMultiplier;
	}

	public HashMap<Material, Float> getItemBuyPrice() {
		return itemBuyPrice;
	}

	public void setItemBuyPrice(HashMap<Material, Float> itemBuyPrice) {
		this.itemBuyPrice = itemBuyPrice;
	}

	public HashMap<Material, Float> getItemSellPrice() {
		return itemSellPrice;
	}

	public void setItemSellPrice(HashMap<Material, Float> itemSellPrice) {
		this.itemSellPrice = itemSellPrice;
	}
	
	
	
	
}
