name: CustomEssentials
api-version: 1.13
version: 1.0.0
author: GenjutsuUser
main: CustomEssentials.Main
description: Custom Essentials
commands:
  fly: 
  feed:
  eat: 
  menu: 
  espawn:
  weapon:
  skills:
  pathSelector:
  balance:
  bal:
  money:
  pay:
  shop:
  market:
  shopBlocks1:
  shopBlocks2:
  shopBlocks3:
  shopBlocks4:
  shopColorBlocks1:
  shopColorBlocks2:
  shopDecorativeBlocks1:
  shopDecorativeBlocks2:
  shopFarming1:
  shopFarming2:
  shopMob1:
  shopMob2:
  shopFood1:
  shopFood2:
  shopGems1:
  shopGems2:
  shopMisc1:
  shopMisc2:
  shopMobDrops1:
  shopMobDrops2:
  shopRedstone1:
  shopRedstone2:
  shopBrewing1:
  shopBrewing2:

  